module.exports = [
  'a group of cats is called a clowder.',
  'cats are the most popular pet in the United States; there are 88 million pet cats and 74 million dogs.',
  'there are cats who have survived falls from over 32 stories (320 meters) onto concrete.',
  'cats have over 20 muscles that control their ears.',
  'cats sleep 70% of their lives.',
  'a cat has been mayor of Talkeetna, Alaska, for 15 years. His name is Stubbs.',
  'one cat ran for mayor of Mexico City in 2013.',
  'in tigers and tabbies, the middle of the tongue is covered in backward-pointing spines, used for breaking off and gripping meat.',
  'when cats grimace, they are usually “taste-scenting.” They have an extra organ that, with some breathing control, allows the cats to taste-sense the air.',
  'cats can’t taste sweetness.',
  'owning a cat can reduce the risk of stroke and heart attack by a third.',
  'wikipedia has a recording of a cat meowing because why not?',
  'the world’s largest cat measured 48.5 inches long.',
  'evidence suggests domesticated cats have been around since 3600 B.C., 2,000 years before Egypt’s pharaohs.',
  'a cat’s purr may be a form of self-healing, as it can be a sign of nervousness as well as contentment.',
  'similarly, the frequency of a domestic cat’s purr is the same at which muscles and bones repair themselves.',
  'adult cats only meow to communicate with humans.',
  'the world’s richest cat is worth $13 million after his human passed away and left her fortune to him.',
  'your cat recognizes your voice but just acts too cool to care (probably because they are).',
  'cats are often lactose intolerant, so stop givin’ them milk!',
  'basically all cartoon cats lied to us: Raw fish is off the table for cats as well.',
  'the oldest cat video on YouTube dates back to 1894 (when it was made, not when it was uploaded, duh).',
  'in the 1960s, the CIA tried to turn a cat into a bonafide spy by implanting a microphone into her ear and a radio transmitter at the base of her skull. She somehow survived the surgery but got hit by a taxi on her first mission.',
  'the technical term for “hairball” is “bezoar.”',
  'female cats are typically right-pawed while male cats are typically left-pawed.',
  'cats make more than 100 different sounds whereas dogs make around 10.',
  'a cat’s brain is 90% similar to a human’s — more similar than to a dog’s.',
  'cats and humans have nearly identical sections of the brain that control emotion.',
  'a cat’s cerebral cortex (the part of the brain in charge of cognitive information processing) has 300 million neurons, compared with a dog’s 160 million.',
  'cats have a longer-term memory than dogs, especially when they learn by actually doing rather than simply seeing.',
  'basically, cats have a lower social IQ than dogs but can solve more difficult cognitive problems when they feel like it.',
  'cats have 1,000 times more data storage than an iPad.',
  'it was illegal to slay cats in ancient Egypt, in large part because they provided the great service of controlling the rat population.',
  'in the 15th century, Pope Innocent VIII began ordering the killing of cats, pronouncing them demonic.',
  'a cat has five toes on his front paws, and four on the back, unless he’s a polydactyl.',
  'polydactyl cats are also referred to as “Hemingway cats” because the author was so fond of them.',
  'there are 45 Hemingway cats living at the author’s former home in Key West, Fla.',
  'original kitty litter was made out of sand but it was replaced by more absorbent clay in 1948.',
  'abraham Lincoln kept four cats in the White House.',
  'when asked if her husband had any hobbies, Mary Todd Lincoln is said to have replied “cats.”',
  'isaac Newton is credited with inventing the cat door.',
  'one legend claims that cats were created when a lion on Noah’s Ark sneezed and two kittens came out.',
  'a cat can jump up to six times its length.',
  'a house cat is faster than Usain Bolt.',
  'when cats leave their poop uncovered, it is a sign of aggression to let you know they don’t fear you.',
  'cats can change their meow to manipulate a human. They often imitate a human baby when they need food, for example.',
  'cats use their whiskers to detect if they can fit through a space.',
  'cats only sweat through their foot pads.',
  'the first cat in space was French. She was named Felicette, or “Astrocat.” She survived the trip.',
  'cats have free-floating clavicle bones that attach their shoulders to their forelimbs, which allows them to squeeze through very small spaces.',
  'hearing is the strongest of cat’s senses: They can hear sounds as high as 64 kHz — compared with humans, who can hear only as high as 20 kHz.',
  'cats can move their ears 180 degrees.',
  'a cat has detected his human’s breast cancer.',
  'a cat’s nose is ridged with a unique pattern, just like a human fingerprint.',
  'cats have scent glands along their tail, their forehead, lips, chin, and the underside of their front paws.',
  'a cat rubs against people to mark its territory.',
  'cats lick themselves to get your scent off.',
  'when a family cat died in ancient Egypt, family members would shave off their eyebrows as they mourned.',
  'they also had elaborate memorials that included mummifying the cat and either burying it in a family tomb or pet cemetery.',
  'cats were mythic symbols of divinity in ancient Egypt.',
  'black cats are bad luck in the United States, but they are good luck in the United Kingdom and Australia.',
  'most cats don’t like water because their coats do not insulate them well enough.',
  'a cat called the Turkish Van does not have that insulation problem and LOVES it.',
  'the Egyptian Mau is the oldest breed of cat.',
  'the Egyptian Mau is the fastest pedigreed cat.',
  'the Egyptian word for cat is, in fact, “mau.”',
  'only 11.5% of people consider themselves “cat people.”\n',
  'cat people are also 11% more likely to be introverted.',
  'cat people are more open to new experiences than typical “dog people.”',
  'cat owners who are male tend to be luckier in love, as they are perceived as more sensitive.g',
  'cat owners are 17% more likely to have a graduate degree.',
  'cat people are 25% likely to pick George as their favorite Beatle.',
  'a cat’s carbon footprint is similar to that of a VW Bug, whereas a dog’s is more like a Hummer.',
  'when your cat brings home a dead mouse or bird, it may do so to show you that you suck at hunting.',
  'cats have inferior daytime sight, but during the night they need seven times less light than humans to see.',
  'the largest litter of kittens produced 19 kittens.',
  'eighty-eight percent of cats in the U.S. are spayed or neutered.',
  'only 24% of cats who enter animal shelters are adopted.',
  'cats are really cool.',
  'cats are also very soft.',
  "Tabby cats are thought to get their name from Attab a district in Baghdad now the capital of Iraq.",
  "The cat appears to be the only domestic companion animal not mentioned in the Bible.",
  "The heaviest cat on record is Himmy a Tabby from Queensland Australia. He weighed nearly 47 pounds (21 kg). He died at the age of 10.",
  "The lightest cat on record is a blue point Himalayan called Tinker Toy who weighed 1 pound 6 ounces (616 g). Tinker Toy was 2.75 inches (7 cm) tall and 7.5 inches (19 cm) long.",
  "A cat's field of vision is about 200 degrees.",
  "In Siam the cat was so revered that one rode in a chariot at the head of a parade celebrating the new king.",
  "Cats have 32 muscles that control the outer ear (humans have only 6). A cat can independently rotate its ears 180 degrees.",
  "Tylenol and chocolate are both poisionous to cats.",
  "A cat sees about 6 times better than a human at night and needs 1/6 the amount of of light that a human does - it has a layer of extra reflecting cells which absorb light.",
  "Spanish-Jewish folklore recounts that Adam’s first wife Lilith became a black vampire cat sucking the blood from sleeping babies. This may be the root of the superstition that a cat will smother a sleeping baby or suck out the child’s breath.",
  "Cats should not be fed tuna exclusively as it lacks taurine an essential nutrient required for good feline health.  Make sure you have the proper Pet supplies to keep your cat happy and healthy.",
  "Abraham Lincoln loved cats. He had four of them while he lived in the White House.",
  "It may take as long as 2 weeks for a kitten to be able to hear well.  Their eyes usually open between 7 and 10 days but sometimes it happens in as little as 2 days.",
  "A cat’s hearing is better than a dog’s. And a cat can hear high-frequency sounds up to two octaves higher than a human.",
  "Cats step with both left legs then both right legs when they walk or run.",
  "Cats purr at the same frequency as an idling diesel engine about 26 cycles per second.",
  "In 1987 cats overtook dogs as the number one pet in America (about 50 million cats resided in 24 million homes in 1986). About 37% of American homes today have at least one cat.",
  "Cats have 32 muscles that control the outer ear (compared to human's 6 muscles each). A cat can rotate its ears independently 180 degrees and can turn in the direction of sound 10 times faster than those of the best watchdog.",
  "A cat named Dusty aged 1 7 living in Bonham Texas USA gave birth to her 420th kitten on June 23 1952.",
  "A cat's brain is more similar to a man's brain than that of a dog.",
  "Female cats tend to be right pawed while male cats are more often left pawed. Interestingly while 90% of humans are right handed the remaining 10% of lefties also tend to be male.",
  "The group of words associated with cat (catt cath chat katze) stem from the Latin catus meaning domestic cat as opposed to feles or wild cat.",
  "There are up to 60 million feral cats in the United States alone.",
  "The average lifespan of an outdoor-only (feral and non-feral) is about 3 years; an indoor-only cat can live 16 years and longer. Some cats have been documented to have a longevity of 34 years.",
  "A cat has approximately 60 to 80 million olfactory cells (a human has between 5 and 20 million).",
  "The world’s rarest coffee Kopi Luwak comes from Indonesia where a wildcat known as the luwak lives. The cat eats coffee berries and the coffee beans inside pass through the stomach. The beans are harvested from the cat’s dung heaps and then cleaned and roasted. Kopi Luwak sells for about $500 for a 450 g (1 lb) bag.",
  "A cat usually has about 12 whiskers on each side of its face.",
  "The largest cat breed is the Ragdoll. Male Ragdolls weigh between 12 and 20 lbs (5.4-9.0 k). Females weigh between 10 and 15 lbs (4.5-6.8 k).",
  "The first cartoon cat was Felix the Cat in 1919. In 1940 Tom and Jerry starred in the first theatrical cartoon “Puss Gets the Boot.” In 1981 Andrew Lloyd Weber created the musical Cats based on T.S. Eliot’s Old Possum’s Book of Practical Cats.",
  "Purring does not always indicate that a cat is happy. Cats will also purr loudly when they are distressed or in pain.",
  "Unlike humans cats do not need to blink their eyes on a regular basis to keep their eyes lubricated.",
  "The cat's footpads absorb the shocks of the landing when the cat jumps.",
  "The average litter of kittens is between 2 - 6 kittens.",
  "According to a Gallup poll most American pet owners obtain their cats by adopting strays.",
  "Cats sleep 16 to 18 hours per day. When cats are asleep they are still alert to incoming stimuli. If you poke the tail of a sleeping cat it will respond accordingly.",
  "All cats have three sets of long hairs that are sensitive to pressure - whiskers eyebrowsand the hairs between their paw pads.",
  "The average lifespan of an outdoor-only cat is about 3 to 5 years while an indoor-only cat can live 16 years or much longer.",
  "Some common houseplants poisonous to cats include: English Ivy iris mistletoe philodendron and yew.",
  "In just 7 years one un-spayed female cat and one un-neutered male cat and their offspring can result in 420000 kittens.",
  "It has been scientifically proven that owning cats is good for our health and can decrease the occurrence of high blood pressure and other illnesses.",
  "A cat's hearing is much more sensitive than humans and dogs.",
  "It is estimated that cats can make over 60 different sounds.",
  "Cats have about 130000 hairs per square inch (20155 hairs per square centimeter).",
  "The domestic cat is the only species able to hold its tail vertically while walking. You can also learn about your cat's present state of mind by observing the posture of his tail.",
  "Cats and kittens should be acquired in pairs whenever possible as cat families interact best in pairs.",
  "The life expectancy of cats has nearly doubled since 1930 - from 8 to 16 years.",
  "Researchers are unsure exactly how a cat purrs. Most veterinarians believe that a cat purrs by vibrating vocal folds deep in the throat. To do this a muscle in the larynx opens and closes the air passage about 25 times per second.",
  "The oldest cat to give birth was Kitty who at the age of 30 gave birth to two kittens. During her life she gave birth to 218 kittens.",
  "At 4 weeks it is important to play with kittens so that they do not develope a fear of people.",
  "The cat has 500 skeletal muscles (humans have 650).",
  "The first cat show was organized in 1871 in London. Cat shows later became a worldwide craze.",
  "Most cats give birth to a litter of between one and nine kittens. The largest known litter ever produced was 19 kittens of which 15 survived.",
  "The Maine Coon is 4 to 5 times larger than the Singapura the smallest breed of cat.",
  "An adult lion's roar can be heard up to five miles (eight kilometers) away.",
  "A cat will tremble or shiver when it is extreme pain.",
  "Cats are subject to gum disease and to dental caries. They should have their teeth cleaned by the vet or the cat dentist once a year.",
  "The way you treat kittens in the early stages of it's life will render it's personality traits later in life.",
  "In an average year cat owners in the United States spend over $2 billion on cat food.",
  "Cats walk on their toes.",
  "Cats eat grass to aid their digestion and to help them get rid of any fur in their stomachs.",
  "Two members of the cat family are distinct from all others: the clouded leopard and the cheetah. The clouded leopard does not roar like other big cats nor does it groom or rest like small cats. The cheetah is unique because it is a running cat; all others are leaping cats. They are leaping cats because they slowly stalk their prey and then leap on it.",
  "Cats often overract to unexpected stimuli because of their extremely sensitive nervous system.",
  "The ancestor of all domestic cats is the African Wild Cat which still exists today.",
  "The first commercially cloned pet was a cat named Little Nicky. He cost his owner $50000 making him one of the most expensive cats ever.",
  "People who are allergic to cats are actually allergic to cat saliva or to cat dander. If the resident cat is bathed regularly the allergic people tolerate it better.",
  "A female cat will be pregnant for approximately 9 weeks or between 62 and 65 days from conception to delivery.",
  "While many parts of Europe and North America consider the black cat a sign of bad luck in Britain and Australia black cats are considered lucky.",
  "The first cat in space was a French cat named Felicette (a.k.a. “Astrocat”) In 1963 France blasted the cat into outer space. Electrodes implanted in her brains sent neurological signals back to Earth. She survived the trip.",
  "Cat paws act as tempetature regulators shock absorbers hunting and grooming tools sensors and more",
  "Cheetahs do not roar as the other big cats do. Instead they purr.",
  "While it is commonly thought that the ancient Egyptians were the first to domesticate cats the oldest known pet cat was recently found in a 9500-year-old grave on the Mediterranean island of Cyprus. This grave predates early Egyptian art depicting cats by 4000 years or more.",
  "Cats have the largest eyes of any mammal.",
  "The largest breed of cat is the Ragdoll with males weighing in at 1 5 to 20 lbs. The heaviest domestic cat on record was a neutered male tabby named Himmy from Queensland Australia who weighed 46 lbs. 1 5 oz.",
  "The tiniest cat on record is Mr. Pebbles a 2-year-old cat that weighed 3 lbs (1.3 k) and was 6.1 inches (15.5 cm) high.",
  "In Japan cats are thought to have the power to turn into super spirits when they die. This may be because according to the Buddhist religion the body of the cat is the temporary resting place of very spiritual people.i",
  "Cats see six times better in the dark and at night than humans.",
  "Cats are now Britain's favourite pet: there are 7.7 million cats as opposed to 6.6 million dogs.",
  "If they have ample water cats can tolerate temperatures up to 133 °F.",
  "A cats field of vision is about 185 degrees.",
  "It has been scientifically proven that stroking a cat can lower one's blood pressure.",
  "Most cats had short hair until about 100 years ago when it became fashionable to own cats and experiment with breeding.",
  "A sexually-active feral tom-cat owns an area of about three square miles and sprays to mark his territory with strong smelling urine.",
  "Many cats cannot properly digest cow's milk. Milk and milk products give them diarrhea.",
  "Approximately 1/3 of cat owners think their pets are able to read their minds.",
  "A cat’s nose pad is ridged with a unique pattern just like the fingerprint of a human.",
  "Retractable claws are a physical phenomenon that sets cats apart from the rest of the animal kingdom. I n the cat family only cheetahs cannot retract their claws.",
  "A cat will tremble or shiver when it is in extreme pain.",
  "Cat's urine glows under a black light.",
  "Kittens who are taken along on short trouble-free car trips to town tend to make good passengers when they get older. They get used to the sounds and motions of traveling and make less connection between the car and the visits to the vet.",
  "A domestic cat can run at speeds of 30 mph.",
  "In the 1750s Europeans introduced cats into the Americas to control pests.",
  "Lions are the only cats that live in groups called prides. Every female within the pride is usually related.",
  "Contrary to popular belief the cat is a social animal. A pet cat will respond and answer to speech  and seems to enjoy human companionship.",
  "Unlike other cats lions have a tuft of hair at the end of their tails.",
  "A cat has more bones than a human; humans have 206 but the cat has 230 (some cites list 245 bones and state that bones may fuse together as the cat ages).",
  "The first true cats came into existence about 12 million years ago and were the Proailurus.",
  "Today there are about 100 distinct breeds of the domestic cat.",
  "There are approximately 60000 hairs per square inch on the back of a cat and about 120000 per square inch on its underside.",
  "If a cat is frightened the hair stands up fairly evenly all over the body; when the cat is threatened or is ready to attack the hair stands up only in a narrow band along the spine and tail.",
  "Cats take between 20-40 breaths per minute.",
  "Most cats sleep around 16 hours a day",
  "The leopard is the most widespread of all big cats.",
  "The average cat food meal is the equivalent to about five mice.",
  "A cat uses its whiskers for measuring distances.  The whiskers of a cat are capable of registering very small changes in air pressure.",
  "Cats make about 100 different sounds. Dogs make only about 10.",
  "Miacis the primitive ancestor of cats was a small tree-living creature of the late Eocene period some 45 to 50 million years ago.",
  "Ancient Egyptian family members shaved their eyebrows in mourning when the family cat died.",
  "In ancient Egypt mummies were made of cats and embalmed mice were placed with them in their tombs. In one ancient city over 300000 cat mummies were found.",
  "A female cat is called a queen or a molly.",
  "The cat who holds the record for the longest non-fatal fall is Andy. He fell from the 16th floor of an apartment building (about 200 ft/.06 km) and survived.",
  "Many people in China consider cats a warming food that is perfect to eat during the winter",
  "All cats have claws and all except the cheetah sheath them when at rest.",
  "Most cats adore sardines.",
  "A cat's normal temperature varies around 101 degrees Fahrenheit.",
  "On average cats spend 2/3 of every day sleeping. That means a nine-year-old cat has been awake for only three years of its life.",
  "Kittens remain with their mother till the age of 9 weeks.",
  "A queen (female cat) can begin mating when she is between 5 and 9 months old.",
  "omgdatbanhammer  In 1987 cats overtook dogs as the number one pet in America.",
  "A cat almost never meows at another cat mostly just humans. Cats typically will spit purr and hiss at other cats.",
  "Cats lose almost as much fluid in the saliva while grooming themselves as they do through urination.",
  "In multi-cat households cats of the opposite sex usually get along better.",
  "Jaguars are the only big cats that don't roar.",
  "A cat's normal pulse is 140-240 beats per minute with an average of 195.",
  "A commemorative tower was built in Scotland for a cat named Towser who caught nearly 30000 mice in her lifetime.",
  "The name jaguar comes from a Native American word meaning he who kills with one leap.",
  "Cats can jump up to 7 times their tail length.",
  "A cat's normal pulse is 140-240 beats per minute with an average of 195.",
  "The most expensive cat was an Asian Leopard cat (ALC)-Domestic Shorthair (DSH) hybrid named Zeus. Zeus who is 90% ALC and 10% DSH has an asking price of £100000 ($154000).",
  "A 2007 Gallup poll revealed that both men and women were equally likely to own a cat.",
  "Heat occurs several times a year and can last anywhere from 3 to 15 days.",
  "Normal body temperature for a cat is 102 degrees F.",
  "Grown cats have 30 teeth. Kittens have about 26 temporary teeth which they lose when they are about 6 months old.",
  "Cats respond better to women than to men probably due to the fact that women's voices have a higher pitch.",
  "In the 1930s two Russian biologists discovered that color change in Siamese kittens depend on their body temperature. Siamese cats carry albino genes that work only when the body temperature is above 98° F. If these kittens are left in a very warm room their points won’t darken and they will stay a creamy white.",
  "Foods that should not be given to cats include onions garlic green tomatoes raw potatoes chocolate grapes and raisins. Though milk is not toxic it can cause an upset stomach and gas. Tylenol and aspirin are extremely toxic to cats as are many common houseplants. Feeding cats dog food or canned tuna that’s for human consumption can cause malnutrition.",
  "Cats' hearing stops at 65 khz (kilohertz); humans' hearing stops at 20 khz.",
  "The cat's tail is used to maintain balance.",
  "Cats' eyes shine in the dark because of the tapetum a reflective layer in the eye which acts like a mirror.",
  "In contrast to dogs cats have not undergone major changes during their domestication process.",
  "When a family cat died in ancient Egypt family members would mourn by shaving off their eyebrows. They also held elaborate funerals during which they drank wine and beat their breasts. The cat was embalmed with a sculpted wooden mask and the tiny mummy was placed in the family tomb or in a pet cemetery with tiny mummies of mice.",
  "A kitten will typically weigh about 3 ounces at birth.  The typical male housecat will weigh between  7 and 9 pounds slightly less for female housecats.",
  "Cats have nine lives thanks to a flexible spine and powerful leg and back muscles",
  "Both humans and cats have identical regions in the brain responsible for emotion.",
  "Florence Nightingale owned more than 60 cats in her lifetime.",
  "Cats do not think that they are little people. They think that we are big cats. This influences their behavior in many ways.",
  "Female felines are superfecund",
  "Cats have 30 teeth (12 incisors 10 premolars 4 canines and 4 molars) while dogs have 42. Kittens have baby teeth which are replaced by permanent teeth around the age of 7 months.",
  "A cat rubs against people not only to be affectionate but also to mark out its territory with scent glands around its face. The tail area and paws also carry the cat’s scent.",
  "According to Hebrew legend Noah prayed to God for help protecting all the food he stored on the ark from being eaten by rats. In reply God made the lion sneeze and out popped a cat.",
  "Cats can predict earthquakes. We humans are not 100% sure how they do it. There are several different theories.",
  "A tiger's stripes are like fingerprints̢",
  "When a cat drinks its tongue - which has tiny barbs on it - scoops the liquid up backwards.",
  "Mohammed loved cats and reportedly his favorite cat Muezza was a tabby. Legend says that tabby cats have an “M” for Mohammed on top of their heads because Mohammad would often rest his hand on the cat’s head.",
  "A cat’s eyesight is both better and worse than humans. It is better because cats can see in much dimmer light and they have a wider peripheral view. It’s worse because they don’t see color as well as humans do. Scientists believe grass appears red to cats.",
  "The cat's clavicle or collarbone does not connect with other bones but is buried in the muscles of the shoulder region. This lack of a functioning collarbone allows them to fit through any opening the size of their head.",
  "The silks created by weavers in Baghdad were inspired by the beautiful and varied colors and markings of cat coats. These fabrics were called tabby by European traders.",
  "A cat’s brain is biologically more similar to a human brain than it is to a dog’s. Both humans and cats have identical regions in their brains that are responsible for emotions.",
  "Like birds cats have a homing ability that uses its biological clock the angle of the sun and the Earth's magnetic field. A cat taken far from its home can return to it. But if a cat's owners move far from its home the cat can't find them.",
  "All cats need taurine in their diet to avoid blindness. Cats must also have fat in their diet as they are unable to produce it on their own.",
  "Cats have 300 million neurons; dogs have about 160 million",
  "Cats hate the water because their fur does not insulate well when it’s wet. The Turkish Van however is one cat that likes swimming. Bred in central Asia its coat has a unique texture that makes it water resistant.",
  "Cats can be taught to walk on a leash but a lot of time and patience is required to teach them. The younger the cat is the easier it will be for them to learn.",
  "Neutering a cat extends its life span by two or three years.",
  "Relative to its body size the clouded leopard has the biggest canines of all animals’ canines. Its dagger-like teeth can be as long as 1.8 inches (4.5 cm).",
  "The life expectancy of cats has nearly doubled over the last fifty years.",
  "On average a cat will sleep for 16 hours a day.",
  "Blue-eyed white cats are often prone to deafness.",
  "Cats have 30 vertebrae (humans have 33 vertebrae during early development; 26 after the sacral and coccygeal regions fuse)",
  "A steady diet of dog food may cause blindness in your cat - it lacks taurine.",
  "Cats respond most readily to names that end in an ee sound.",
  "During the time of the Spanish Inquisition Pope Innocent VIII condemned cats as evil and thousands of cats were burned. Unfortunately the widespread killing of cats led to an explosion of the rat population which exacerbated the effects of the Black Death.",
  "The ability of a cat to find its way home is called “psi-traveling.” Experts think cats either use the angle of the sunlight to find their way or that cats have magnetized cells in their brains that act as compasses.",
  "Cats are the world's most popular pets outnumbering dogs by as many as three to one",
  "Cats must have fat in their diet because they can't produce it on their own.",
  "Cats are extremely sensitive to vibrations. Cats are said to detect earthquake tremors 10 or 15 minutes before humans can.",
  "Cats control the outer ear using 32 muscles; humans use 6",
  "Cats lap liquid from the underside of their tongue not from the top.",
  "About 37% of American homes today have at least 1 cat.",
  "A cat can spend five or more hours a day grooming himself.",
  "The first formal cat show was held in England in 1871; in America in 1895.",
  "Not every cat gets high from catnip. If the cat doesn't have a specific gene",
  "A cat lover is called an Ailurophilia (Greek: cat+lover).",
  "A cat cannot see directly under its nose.",
  "The normal body temperature of a cat is between 100.5 ° and 102.5 °F. A cat is sick if its temperature goes below 100 ° or above 103 °F.",
  "The cat appears to be the only domestic companion animal not mentioned in the Bible.",
  "The Egyptian Mau is probably the oldest breed of cat. In fact the breed is so ancient that its name is the Egyptian word for “cat.”",
  "The strongest climber among the big cats a leopard can carry prey twice its weight up a tree.",
  "A form of AIDS exists in cats.",
  "The Pilgrims were the first to introduce cats to North America.",
  "Cats have supersonic hearing",
  "Fossil records from two million years ago show evidence of jaguars.",
  "The most popular pedigreed cat is the Persian cat followed by the Main Coon cat and the Siamese cat.",
  "Mountain lions are strong jumpers thanks to muscular hind legs that are longer than their front legs.",
  "Every time you masturbate God kills a kitten. Please think of the kittens.",
  "There is a species of cat smaller than the average housecat. It is native to Africa and it is the Black-footed cat (Felis nigripes). Its top weight is 5.5 pounds.",
  "Some Siamese cats appear cross-eyed because the nerves from the left side of the brain go to mostly the right eye and the nerves from the right side of the brain go mostly to the left eye. This causes some double vision which the cat tries to correct by “crossing” its eyes.",
  "A cat's whiskers are thought to be a kind of radar which helps a cat gauge the space it intends to walk through.",
  "Cats that live together sometimes rub each others heads to show that they have no intention of fighting. Young cats do this more often especially when they are excited.",
  "The richest cat is Blackie who was left £15 million by his owner Ben Rea.",
  "A cat’s back is extremely flexible because it has up to 53 loosely fitting vertebrae. Humans only have 34.",
  "A cat called Dusty has the known record for the most kittens. She had more than 420 kittens in her lifetime.",
  "Siamese kittens are born white because of the heat inside the mother's uterus before birth. This heat keeps the kittens' hair from darkening on the points.",
  "In the original Italian version of Cinderella the benevolent fairy godmother figure was a cat.",
  "If your cat snores or rolls over on his back to expose his belly it means he trusts you.",
  "The biggest wildcat today is the Siberian Tiger. It can be more than 12 feet (3.6 m) long (about the size of a small car) and weigh up to 700 pounds (317 kg).",
  "While many cats enjoy milk it will give some cats diarrhea.",
  "You check your cats pulse on the inside of the back thigh where the leg joins to the body. Normal for cats: 110-170 beats per minute.",
  "A cat has more bones than a human; humans have 206 and the cat - 230.",
  "A happy cat holds her tail high and steady.",
  "The claws on the cat’s back paws aren’t as sharp as the claws on the front paws because the claws in the back don’t retract and consequently become worn.",
  "In Holland’s embassy in Moscow Russia the staff noticed that the two Siamese cats kept meowing and clawing at the walls of the building. Their owners finally investigated thinking they would find mice. Instead they discovered microphones hidden by Russian spies. The cats heard the microphones when they turned on.",
  "Of all the species of cats the domestic cat is the only species able to hold its tail vertically while walking. All species of wild cats hold their tail horizontally or tucked between their legs while walking.",
  "Ailurophile is the word cat lovers are officially called.",
  "A cat has two vocal chords and can make over 100 sounds.",
  "A cat has 230 bones in its body. A human has 206. A cat has no collarbone so it can fit through any opening the size of its head.",
  "A cat can jump 5 times as high as it is tall.",
  "Cats especially older cats do get cancer. Many times this disease can be treated successfully.",
  "Purring does not always indicate that a cat is happy and healthy - some cats will purr loudly when they are terrified or in pain.",
  "A cat's jaw has only up and down motion; it does not have any lateral side to side motion like dogs and humans.",
  "Isaac Newton invented the cat flap. Newton was experimenting in a pitch-black room. Spithead one of his cats kept opening the door and wrecking his experiment. The cat flap kept both Newton and Spithead happy.",
  "One reason that kittens sleep so much is because a growth hormone is released only during sleep.",
  "Perhaps the most famous comic cat is the Cheshire Cat in Lewis Carroll’s Alice in Wonderland. With the ability to disappear this mysterious character embodies the magic and sorcery historically associated with cats.",
  "Some cats have survived falls of over 65 feet (20 meters) due largely to their “righting reflex.” The eyes and balance organs in the inner ear tell it where it is in space so the cat can land on its feet. Even cats without a tail have this ability.",
  "A cat can sprint at about thirty-one miles per hour.",
  "The most traveled cat is Hamlet who escaped from his carrier while on a flight. He hid for seven weeks behind a panel on the airplane. By the time he was discovered he had traveled nearly 373000 miles (600000 km).",
  "Baking chocolate is the most dangerous chocolate to your cat.",
  "A tomcat (male cat) can begin mating when he is between 7 and 10 months old.",
  "The earliest ancestor of the modern cat lived about 30 million years ago. Scientists called it the Proailurus which means “first cat” in Greek. The group of animals that pet cats belong to emerged around 12 million years ago.",
  "The oldest cat on record was Crème Puff from Austin Texas who lived from 1967 to August 6 2005 three days after her 38th birthday. A cat typically can live up to 20 years which is equivalent to about 96 human years.",
  "The first cat show was in 1871 at the Crystal Palace in London.",
  "Milk can give some cats diarrhea.",
  "Unlike dogs cats do not have a sweet tooth. Scientists believe this is due to a mutation in a key taste receptor.",
  "The Amur leopard is one of the most endangered animals in the world.",
  "When a cats rubs up against you the cat is marking you with it's scent claiming ownership.",
  "Cats spend nearly 1/3 of their waking hours cleaning themselves.",
  "Like humans cats tend to favor one paw over another",
  "Cats' hearing is much more sensitive than humans and dogs.",
  "The first official cat show in the UK was organised at Crystal Palace in 1871.",
  "The female cat reaches sexual maturity within 6 to 10 months; most veterinarians suggest spaying the female at 5 months before her first heat period. The male cat usually reaches sexual maturity between 9 and 12 months.",
  "In just seven years a single pair of cats and their offspring could produce a staggering total of 420000 kittens.",
  "Cats with long lean bodies are more likely to be outgoing and more protective and vocal than those with a stocky build.",
  "In ancient Egypt when a family cat died all family members would shave their eyebrows as a sign of mourning.",
  "Approximately 40000 people are bitten by cats in the U.S. annually.",
  "Statistics indicate that animal lovers in recent years have shown a preference for cats over dogs!",
  "A healthy cat has a temperature between 38 and 39 degrees Celcius.",
  "Julius Ceasar Henri II Charles XI and Napoleon were all afraid of cats.",
  "The chlorine in fresh tap water irritates sensitive parts of the cat's nose. Let tap water sit for 24 hours before giving it to a cat.",
  "Cat bites are more likely to become infected than dog bites.",
  "Phoenician cargo ships are thought to have brought the first domesticated cats to Europe in about 900 BC.",
  "Edward Lear author of The Owl and the Pussycat is said to have had his new house in San Remo built to exactly the same specification as his previous residence so that his much-loved tabby Foss would immediately feel at home.",
  "Long muscular hind legs enable snow leopards to leap seven times their own body length in a single bound.",
  "Tigers are excellent swimmers and do not avoid water.",
  "Cats have individual preferences for scratching surfaces and angles. Some are horizontal scratchers while others exercise their claws vertically.",
  "Some notable people who disliked cats:  Napoleon Bonaparte Dwight D. Eisenhower Hitler.",
  "In 1987 cats overtook dogs as the number one pet in America.",
  "Cats come back to full alertness from the sleep state faster than any other creature.",
  "In relation to their body size cats have the largest eyes of any mammal.",
  "Cats can be right-pawed or left-pawed.",
  "A cat will tremble or shiver when it is extreme pain.",
  "Many Egyptians worshipped the goddess Bast who had a woman’s body and a cat’s head.",
  "In 1888 more than 300000 mummified cats were found an Egyptian cemetery. They were stripped of their wrappings and carted off to be used by farmers in England and the U.S. for fertilizer.",
  "The little tufts of hair in a cat’s ear that help keep out dirt direct sounds into the ear and insulate the ears are called “ear furnishings.”",
  "An adult lion's roar can be heard up to five miles (eight kilometers) away.",
  "Cats lived with soldiers in trenches where they killed mice during World War I.",
  "In one stride a cheetah can cover 23 to 26 feet (7 to 8 meters).",
  "The Maine Coone is the only native American long haired breed.",
  "There are approximately 100 breeds of cat.",
  "A cat can travel at a top speed of approximately 31 mph (49 km) over a short distance.",
  "A cat’s jaw can’t move sideways so a cat can’t chew large chunks of food.",
  "Approximately 24 cat skins can make a coat.",
  "Cats have been domesticated for half as long as dogs have been.",
  "A cat has more bones than a human being; humans have 206 and the cat has 230 bones.",
  "When a cat chases its prey it keeps its head level. Dogs and humans bob their heads up and down.",
  "Cats bury their feces to cover their trails from predators.",
  "Cats are North America’s most popular pets: there are 73 million cats compared to 63 million dogs. Over 30% of households in North America own a cat.",
  "Cat families usually play best in even numbers. Cats and kittens should be acquired in pairs whenever possible.",
  "The Maine Coon cat is America's only natural breed of domestic feline. It is 4 to 5 times larger than the Singapura the smallest breed of cat.",
  "After humans mountain lions have the largest range of any mammal in the Western Hemisphere.",
  "Among many other diseases cats can suffer from anorexia senility feline AIDS and acne.",
  "Cats just like people are subject to asthma. Dust smoke and other forms of air pullution in your cat's environment can be troublesome sources of irritation.",
  "A cat can’t climb head first down a tree because every claw on a cat’s paw points the same way. To get down from a tree a cat must back down.",
  "Every year nearly four million cats are eaten in Asia.",
  "A cat’s heart beats nearly twice as fast as a human heart at 110 to 140 beats a minute.",
  "Cats dislike citrus scent.",
  "Female cats are polyestrous",
  "The term “puss” is the root of the principal word for “cat” in the Romanian term pisica and the root of secondary words in Lithuanian (puz) and Low German puus. Some scholars suggest that “puss” could be imitative of the hissing sound used to get a cat’s attention. As a slang word for the female pudenda it could be associated with the connotation of a cat being soft warm and fuzzy.",
  "The cat's front paw has 5 toes but the back paws have 4. Some cats are born with as many as 7 front toes and extra back toes (polydactl).",
  "Cats can judge within 3 inches the precise location of a sound being made 1 yard away.",
  "The cheetah is the world's fastest land mammal. It can run at speeds of up to 70 miles an hour (113 kilometers an hour).",
  "A cat's appetite is the barometer of its health. Any cat that does not eat or drink for more than two days should be taken to a vet.",
  "Many cats love having their forehead gently stroked.",
  "Researchers believe the word “tabby” comes from Attabiyah a neighborhood in Baghdad Iraq. Tabbies got their name because their striped coats resembled the famous wavy patterns in the silk produced in this city.",
  "British cat owners spend roughly 550 million pounds yearly on cat food.",
  "Since cats are so good at hiding illness even a single instance of a symptom should be taken very seriously.",
  "The Ancient Egyptian word for cat was mau which means to see.",
  "Tests done by the Behavioral Department of the Musuem of Natural History conclude that while a dog's memory lasts about 5 minutes a cat's recall can last as long as 16 hours.",
  "The technical term for a cat’s hairball is a “bezoar.”",
  "Blue-eyed pure white cats are frequently deaf.",
  "There are more than 500 million domestic cats in the world with approximately 40 recognized breeds.",
  "Neutering a male cat will in almost all cases stop him from spraying (territorial marking) fighting with other males (at least over females) as well as lengthen his life and improve its quality.",
  "The smallest pedigreed cat is a Singapura which can weigh just 4 lbs (1.8 kg) or about five large cans of cat food. The largest pedigreed cats are Maine Coon cats which can weigh 25 lbs (11.3 kg) or nearly twice as much as an average cat weighs.",
  "The smallest wildcat today is the Black-footed cat. The females are less than 20 inches (50 cm) long and can weigh as little as 2.5 lbs (1.2 kg).",
  "Smuggling a cat out of ancient Egypt was punishable by death. Phoenician traders eventually succeeded in smuggling felines which they sold to rich people in Athens and other important cities.",
  "Cats don’t have sweat glands over their bodies like humans do. Instead they sweat only through their paws.",
  "A group of cats is called a “clowder.”",
  "When your cats rubs up against you she is actually marking you as hers with her scent. If your cat pushes his face against your head\"",
  "A cat can jump up to five times its own height in a single bound.",
  "When a domestic cat goes after mice about 1 pounce in 3 results in a catch.",
  "Cat families usually play best in even numbers. Cats and kittens should be aquired in pairs whenever possible."
];
